GET http://localhost:3010/products/

### Does not exist

GET http://localhost:3010/products/2

### Exists d4a142fa-faf6-4c01-a4c0-9fb1339812c0
GET http://localhost:3010/products/d4a142fa-faf6-4c01-a4c0-9fb1339812c0


###
POST http://localhost:3010/products
Content-Type: application/json

{
    "nom" : "charlie DVD",
    "preu" : 30,
    "categoria" : "cinema"
}

###

PUT http://localhost:3010/products/c0808227-edf1-46cf-8010-36704ae60dc7 HTTP/1.1
Content-Type: application/json

{
    "nom" : "miau",
    "preu" : 30,
    "categoria" : "musica"
}

### e975db3b-209a-4519-942a-9b3128dd3721

DELETE  http://localhost:3010/products/e975db3b-209a-4519-942a-9b3128dd3721